charts/SDFactory/Chart.yaml, src/main/java/org/eclipse/tractusx/selfdescriptionfactory/SelfDescriptionFactoryApplication.java, src/main/java/org/eclipse/tractusx/selfdescriptionfactory/Utils.java, src/test/java/org/eclipse/tractusx/selfdescriptionfactory/SelfDescriptionFactoryApplicationTests.java
Helm version : 2.0.1
Image: 2.0.0
=> releasing sd factory major release

CHANGELOG.md, DEPENDENCIES, README.md, charts/sdfactory/Chart.yaml, charts/sdfactory/README.md, pom.xml
- As a part of vulnerability we are upgrading the guava android librabry
=> fix: _Android library update_

.github/workflows/sdfactorypipeline.yml, CHANGELOG.md, README.md, charts/sdfactory/Chart.yaml, charts/sdfactory/README.md, charts/sdfactory/values.yaml, pom.xml
- This PR contains the image to create in docker hub
=> chore: _docker hub image_

.github/workflows/helm-lint.yaml, .github/workflows/helm-upgrade.yaml, CHANGELOG.md, README.md, charts/chart-testing-config.yaml, charts/sdfactory/Chart.yaml, charts/sdfactory/README.md, charts/sdfactory/templates/deployment.yaml, charts/sdfactory/values.yaml, docs/ARC42.md, pom.xml
First merge PR #68 
- This PR consist for fixes for QG4
- Fixes #64
=> feat: _Quality gate fixes_

README.md
Documentation uptade. README file is updated according to the last features SD-Factory supports
=> update README.md according to the last changes

CHANGELOG.md, DEPENDENCIES, pom.xml
- There is an security issue CVE-2023-33202 . This PR will be resolve it.
=> fix: Fix security issue 

CHANGELOG.md, DEPENDENCIES, pom.xml
- This PR consist of vulnerability fix for logback classic & logback core
[CVE-2023-6378](https://avd.aquasec.com/nvd/cve-2023-6378)
- Please merge PR #84 first
=> fix: Vulnerability fix for logback

CHANGELOG.md, README.md, charts/sdfactory/Chart.yaml, charts/sdfactory/README.md
Creating a new release which has fixed multiple security & vulnerability issues
=> docs: new release

.github/workflows/sdfactorypipeline.yml, CHANGELOG.md, charts/sdfactory/templates/deployment.yaml, charts/sdfactory/values.yaml
- Fixes #91 
- This PR helps in creating multi platform image
- Parameterising readiness & liveliness probe in the deployment
- Changing the ImagePullPolicy
=> fix: improve helm chart

CHANGELOG.md, README.md, charts/sdfactory/Chart.yaml, charts/sdfactory/README.md, pom.xml
- This PR is to create a new release 2.1.10 for sdfactory
=> build(2.1.10): create new release

.github/workflows/codeql.yml, README.md, charts/sdfactory/Chart.yaml, charts/sdfactory/README.md
=> chore: Addition of new workflow

.github/dependabot.yml, README.md, charts/sdfactory/Chart.yaml, charts/sdfactory/README.md
- This PR contains the new workflow for dependabot
=> chore: Addition of dependabot

.github/workflows/trivy.yml, README.md, charts/sdfactory/Chart.yaml, charts/sdfactory/README.md
- There are minor changes in the workflow such as severity, exit code.
=> chore: Modification in trivy workflow

.github/workflows/helm-lint.yaml, CHANGELOG.md, DOCKER_NOTICE.md, Dockerfile, README.md, charts/sdfactory/Chart.yaml, charts/sdfactory/README.md, charts/sdfactory/values-beta.yaml, charts/sdfactory/values-dev.yaml, charts/sdfactory/values-int.yaml, charts/sdfactory/values-pen.yaml, pom.xml
This PR is to fix vulnerability & create new release 2.1.11
=> build: create new release

CONTACT.md, README.md
- This PR is for adding the license and contact info in the project.
- Fixes #135
=> docs: Addition of license and contact

.github/workflows/chart-release.yaml, .github/workflows/codeql.yml, .github/workflows/dependencies.yml, .github/workflows/sdfactorypipeline.yml, .github/workflows/trivy.yml
- This PR is to update the action version
=> chore: Upgraded the action versions

CHANGELOG.md, DEPENDENCIES, pom.xml
- Dependabot bump version fixes
=> [Fix|SDF] : Dependabot reported security issues fixed

CHANGELOG.md, README.md
- Updating the api health check URL
=> docs: Update health check URL

README.md, docs/ARC42.md, src/main/resources/application.yml, src/main/resources/static/SDFactoryApi-v22.10.yml, src/test/resources/application.yml
- Modification of few URLs which are not in use.
=> chore: URL modification

CONTRIBUTING.md, LICENSE_non-code, NOTICE.md
- This PR contains the changes w.r.t TRG 7.07, TRG7.08
- Resolves #171 
=> docs: update legal notice

.github/workflows/trivy.yml
Updates:
- retrieves latest release of Trivy versions
- resolves failure of workflows (except High and Critical findings)
`exit-code: "1"`
`limit-severities-for-sarif: true`
=> Chore: Update trivy.yml

CHANGELOG.md, charts/sdfactory/Chart.yaml, charts/sdfactory/README.md, docs/ARC42.md, pom.xml
- Updated Arc42 docs.
- Created new release version.
Please merge PR #221  before this PR
=> build new version

CHANGELOG.md, charts/sdfactory/Chart.yaml, charts/sdfactory/README.md, src/main/resources/application.yml
- Fixed the gaiax policy values
=> chore: gaiax property addition

charts/sdfactory/values-int.yaml
- This PR is to integrate vault into sdfactory, so that it can take values from vault
=> chote: Integration of vault

CHANGELOG.md, src/main/java/org/eclipse/tractusx/selfdescriptionfactory/service/ValidityChecker.java, src/test/java/org/eclipse/tractusx/selfdescriptionfactory/SelfDescriptionFactoryApplicationTests.java, src/test/resources/application.yml
=> Added test cases

src/main/resources/application.yml
- Updated application.yml file
=> - Updated application.yml file

CHANGELOG.md, README.md, charts/sdfactory/Chart.yaml, charts/sdfactory/README.md, pom.xml
- This PR is for creating new version.
=> build: new version release

CHANGELOG.md, README.md, charts/sdfactory/Chart.yaml, pom.xml
- This PR is to create new release.
=> build: New release

CHANGELOG.md, DEPENDENCIES, src/main/java/org/eclipse/tractusx/selfdescriptionfactory/config/DefaultFeignConfig.java
- New changes for code E2010 in service offering.
=>    Service offering changes.

CHANGELOG.md, README.md, charts/sdfactory/Chart.yaml, pom.xml
- This PR is to create new release.
=> build: new release version.

CHANGELOG.md, src/main/java/org/eclipse/tractusx/selfdescriptionfactory/service/converter/tagus/ServiceOfferingSDConverter.java, src/main/resources/application.yml
- Service Offering policy field changes for default.
=> service offering policy changes

CHANGELOG.md, README.md, charts/sdfactory/Chart.yaml, pom.xml
=> build: New release for service offering changes

CHANGELOG.md, DEPENDENCIES, charts/sdfactory/Chart.yaml, charts/sdfactory/README.md, pom.xml
=> build : new release

charts/sdfactory/values.yaml
=> chore: Changed pullPolicy
