eclipse-tractusx/sd-factory

- docs/ARC42.md
- src/main/resources/static/SDFactoryApi.yml
This PR contains 
- a small (rather a decorative) change in OpenAPI service specification;
- ARC42.md file is moved to the docs directory where it is expected to be by convention
> QG5 compatibile arc42 location + schema fix

- charts/sdfactory/templates/tests/test-connection.yaml
As there is nothing in / path, the application responds with 404 so the helm test will fail. Adding the swagger endpoint to the url should solve the test case as it would respond with a 200.
> fix: add swagger endpoint to test connection url

- CHANGELOG.md
- DEPENDENCIES
- README.md
- charts/sdfactory/Chart.yaml
- charts/sdfactory/README.md
- charts/sdfactory/values.yaml
- pom.xml
- src/main/java/org/eclipse/tractusx/selfdescriptionfactory/config/TechnicalUsersDetails.java
- src/main/java/org/eclipse/tractusx/selfdescriptionfactory/service/Claims.java
- Added headers to the files
- Fixes #60
> feat: _addition of header_

- DEPENDENCIES
- src/main/java/org/eclipse/tractusx/selfdescriptionfactory/service/keycloak/KeycloakManager.java
if any of keycloak parameter is missed for a feign service it results in an exeption when token is requested. This fix disables retrieving the token if any parameter is missed.
DEPENDENCIES file is updated. No restrictions are found in the libraries
> keycloak manager fix for tests; update DEPENDENCIES

- CHANGELOG.md
- DEPENDENCIES
- README.md
- charts/sdfactory/Chart.yaml
- charts/sdfactory/README.md
- pom.xml
- To fix the below issue:
Bouncy Castle for Java before 1.73 contains a potential Denial of Service (DoS) issue within the Bouncy Castle org.bouncycastle.openssl.PEMParser class. This class parses OpenSSL PEM encoded streams containing X.509 certificates, PKCS8 encoded keys, and PKCS7 objects. Parsing a file that has crafted ASN.1 data through the PEMParser causes an OutOfMemoryError, which can enable a denial of service attack.
> fix: Security fix for bouncycastle

- CHANGELOG.md
- DEPENDENCIES
- pom.xml
Upgrade of the Spring Boot to the latest available version from 3.1.x branch
with CVE-2023-46589 and CVE-2023-34053 several critical vulnerabilities were found. 3.1.6 contains updated libraries with fixes
> Upgrade of the Spring Boot to get rid of CVE-2023-46589 and CVE-2023-34053

- CHANGELOG.md
- DEPENDENCIES
- pom.xml
- A serialization vulnerability in logback receiver component part of logback version 1.4.13, 1.3.13 and 1.2.12 allows an attacker to mount a Denial-Of-Service attack by sending poisoned data. (https://avd.aquasec.com/nvd/2023/cve-2023-6481/)
- INCORRECT CONVERSION BETWEEN NUMERIC TYPES IN COM.SQUAREUP.OKIO:OKIO CVE-2023-3635
- The libraries were updated to the last unaffected version
- IP was checked with dash-license-tool, no changes are detected
> fix: CVE-2023-6481 and CVE-2023-3635

- CHANGELOG.md
- DEPENDENCIES
- pom.xml
Spring Boot was updated to the version 3.2.2
A number of CVEs were fixed with individual library updates, however with new Spring Boot these updates
were included into the parental project. This is more convenient way for updates
DEPENDENCIES file is up-to-date.  Vetted license information was found for all content. No further investigation is required
> update: Spring Boot update

- CHANGELOG.md
- docs/ARC42.md
- resolves #94 
- removed copyright header and updated notice section
> docs: remove header and add notice

- .github/workflows/dependencies.yml
add workflow for checking dependencies with dash-tool
> chore(ci): check dependencies with dash-tool

- CHANGELOG.md
- INSTALL.md
- charts/sdfactory/README.md
- Closes #97 
- Updated installation steps in INSTALL.md file
> docs: update installation steps

- CHANGELOG.md
- DEPENDENCIES
- pom.xml
new CVEs were found, but were fixed in last Spring Boot
fixes for CVE-2024-22234 and CVE-2024-22243
> fix: upgrade spring boot to 3.2.3

- CHANGELOG.md
- DEPENDENCIES
- pom.xml
Fix CVE-2024-22259 and CVE-2024-22257 security issues
> fix:  CVE-2024-22259 and CVE-2024-22257

- CHANGELOG.md
- DEPENDENCIES
- pom.xml
- CVE-2024-22262 URL Parsing with Host Validation security issue
> [Fix|SDF] : Fixed the CVE-2024-22262

- .github/workflows/helm-lint.yaml
- This PR is to upgrade the kindest/node version tag to v1.27.13
- Resolves #143
> chore: Updated kindest node version tag

- charts/sdfactory/Chart.yaml
- charts/sdfactory/README.md
- charts/sdfactory/values.yaml
fix ingress to work without tls enabled
I noticed that it isn't possible to enable the ingress without TLS enabled as well and that is quite an annoyance if one wants to use the sd-factory in a local testing setup (umbrella), this is due to the following validation: https://github.com/eclipse-tractusx/sd-factory/blob/sdfactory-2.1.18/charts/sdfactory/templates/ingress.yaml#L46
> fix(helm): change ingress to work without tls enabled

- INSTALL.md
- README.md
- charts/sdfactory/Chart.yaml
- charts/sdfactory/README.md
- charts/sdfactory/templates/deployment.yaml
- charts/sdfactory/templates/secret.yaml
- charts/sdfactory/values-beta.yaml
- charts/sdfactory/values-dev.yaml
- charts/sdfactory/values-int.yaml
- charts/sdfactory/values-pen.yaml
- charts/sdfactory/values-test.yaml
- charts/sdfactory/values.yaml
- This PR is to remove the not required secrets as those are removed from the code. Hence not required anymore.
> chore: Removal of unwanted secrets

- .github/workflows/dependencies.yml
- CHANGELOG.md
- DEPENDENCIES
- pom.xml
- In pom version, projectId and test scope added
- Fixes #178
> [Fix|SDF] : Pom changes for dependency check

- CHANGELOG.md
- DEPENDENCIES
- docs/api/openAPI.yaml
- pom.xml
- Current OpenAPI file added under /docs/api directory.
- Dependabot spring, spring-web, spring-security-core, spring cloud, protobuf-javalite and guava version issues fixed.
- Fixes 
> #191 
> #187 
> #184 
> #182 
> #169 
> [Fix|SDF] : Dependabot reported issues fixed

- DEPENDENCIES
- charts/sdfactory/templates/deployment.yaml
- charts/sdfactory/values.yaml
1. This resolves KSV014 from trivy.
2. Is also required by guideline: https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-07/
Activate readOnlyRootFilesystem setting in helm values.
Mount temporary directory to allow writes.
Fixes: #189
> chore(deployment): enable readOnlyRootFilesystem

- .github/workflows/trufflehog.yml
This PR introduces TruffleHog as a new open source tool for secret scanning to be used alongside native Github Secret scanning. This is being enforced as a replacement to the existing GitGuardian (commercial) tool.
[Update trg-8-03.md](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/950)
> chore: Added trufflehog secret scanning tool 

- CHANGELOG.md
- DEPENDENCIES
- pom.xml
- Dependency vulnerability issuse.
- Fixes 
> protobuf-javalite
> commons-io
> spring-security-web
> spring-webmvc
> Dependency vulnerability issues fixed

- AUTHORS.md
- CHANGELOG.md
- DEPENDENCIES
- README.md
- pom.xml
- src/main/java/org/eclipse/tractusx/selfdescriptionfactory/SDFactory.java
- src/main/java/org/eclipse/tractusx/selfdescriptionfactory/SelfDescription.java
- src/main/java/org/eclipse/tractusx/selfdescriptionfactory/Utils.java
- src/main/java/org/eclipse/tractusx/selfdescriptionfactory/config/DefaultFeignConfig.java
- src/main/java/org/eclipse/tractusx/selfdescriptionfactory/service/clearinghouse/ClearingHouse.java
- src/main/java/org/eclipse/tractusx/selfdescriptionfactory/service/converter/RegCodeMapper.java
- src/main/java/org/eclipse/tractusx/selfdescriptionfactory/service/converter/fcformat/LegalParticipantSDConverter.java
- src/main/java/org/eclipse/tractusx/selfdescriptionfactory/service/converter/fcformat/ServiceOfferingSDConverter.java
- src/main/java/org/eclipse/tractusx/selfdescriptionfactory/service/converter/gaiax/LegalParticipantSDConverter.java
- src/main/java/org/eclipse/tractusx/selfdescriptionfactory/service/converter/gaiax/ServiceOfferingSDConverter.java
- src/main/java/org/eclipse/tractusx/selfdescriptionfactory/service/converter/tagus/LegalParticipantSDConverter.java
- src/main/java/org/eclipse/tractusx/selfdescriptionfactory/service/converter/tagus/ServiceOfferingSDConverter.java
- src/main/java/org/eclipse/tractusx/selfdescriptionfactory/service/converter/vrel3/LegalParticipantSDConverter.java
- src/main/java/org/eclipse/tractusx/selfdescriptionfactory/service/converter/vrel3/ServiceOfferingSDConverter.java
- src/main/resources/application.yml
- src/main/resources/static/SDFactoryApi-Tagus.yml
- src/test/resources/application.yml
- Added support for clearing house service new v2 api.
- Readme, Changelog and Dependencies files updated.
> - Gaiax tagus update

- DEPENDENCIES
- README.md
- charts/sdfactory/Chart.yaml
- charts/sdfactory/README.md
- docs/api/openAPI.yaml
- pom.xml
- src/main/resources/static/SDFactoryApi-Tagus.yml
> chore: Updated securit vulnerability
